const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
try{if(localStorage.getItem('solefulTheme')==='dark')document.body.classList.add('dark');}catch{}
const setThemeLabel=()=>$('.theme')?.setAttribute('aria-pressed',String(document.body.classList.contains('dark')));setThemeLabel();
$('.theme')?.addEventListener('click',()=>{document.body.classList.toggle('dark');setThemeLabel();try{localStorage.setItem('solefulTheme',document.body.classList.contains('dark')?'dark':'light');}catch{}});
$('.menu')?.addEventListener('click',()=>{const open=$('.nav-links').classList.toggle('open');$('.menu').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('.nav-links')?.classList.remove('open');$('.menu')?.setAttribute('aria-expanded','false');if($('.lightbox.open'))closeLightbox();$('.chat-box')?.classList.remove('open');}});
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false');});b.classList.add('active');b.setAttribute('aria-pressed','true');$$('.card').forEach(c=>c.hidden=b.dataset.filter!=='all'&&c.dataset.category!==b.dataset.filter);}));
$('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const body=`Name: ${f.get('name')}\nEmail: ${f.get('email')}\n\n${f.get('message')}`;location.href='mailto:info@thesolefulgoddess.com?subject='+encodeURIComponent('Spa website inquiry')+'&body='+encodeURIComponent(body);$('#contactSuccess').textContent='Your email app will open with this draft. Press Send there to deliver it, or call (214) 277-4853.';});
const answers={'Which treatment is right for me?':'Reflexology focuses on the feet. Thai Massage combines stretching and compression. Explore the Services page to choose your session.','What are your hours?':'Open daily from noon to 9 PM at 4425 Plano Pkwy, Suite 803, Carrollton, Texas.','How do I book?':'The Booking page has an interactive demo calendar. Demo reservations stay on your device. To make a real appointment, call (214) 277-4853.'};
$('.chat-toggle')?.addEventListener('click',()=>$('.chat-box').classList.toggle('open'));$('.chat-close')?.addEventListener('click',()=>$('.chat-box').classList.remove('open'));$$('.chat-options button').forEach(b=>b.addEventListener('click',()=>{const p=document.createElement('p');p.textContent=answers[b.dataset.reply];$('.chat-body').append(p);p.scrollIntoView({block:'nearest'});}));
let galleryTrigger;function closeLightbox(){$('.lightbox')?.classList.remove('open');galleryTrigger?.focus();}
$$('.gallery button').forEach(b=>b.addEventListener('click',()=>{galleryTrigger=b;$('.lightbox img').src=b.dataset.image;$('.lightbox img').alt=b.querySelector('img').alt;$('.lightbox').classList.add('open');$('.lightbox').setAttribute('role','dialog');$('.lightbox').setAttribute('aria-label','Gallery image');$('.lightbox-close').setAttribute('aria-label','Close image');$('.lightbox-close').focus();}));$('.lightbox-close')?.addEventListener('click',closeLightbox);$('.lightbox')?.addEventListener('click',e=>{if(e.target===$('.lightbox'))closeLightbox();});
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});$$('.card,.split,.review-card,.band-grid,.contact-grid').forEach(e=>{e.classList.add('reveal');observer.observe(e);});}
